FROM tensorflow/tensorflow:2.15.0

WORKDIR /app
COPY app/detection_service ./detection_service

ENV PYTHONPATH=/app

# Install dependencies
RUN pip install --upgrade pip && \
    pip install --no-cache-dir fastapi uvicorn numpy pydantic

EXPOSE 8000

CMD ["uvicorn", "detection_service.api:app", "--host", "0.0.0.0", "--port", "8000"]